git:
  paging:
    colorArg: always
    pager: delta --24-bit-color=never --paging=never
  pull:
    mode: 'rebase'

gui:
  sidePanelWidth: 0.25
  skipstashwarning: true
  skipunstagelinewarning: false
  theme:
    lighttheme: false
    activeBorderColor:
      - default
      - bold
    inactiveBorderColor:
      - black

startuppopupversion: 1
notARepository: 'skip'
quitOnTopLevelReturn: false
keybinding:
    files:
      commitChanges: 'C'
      commitChangesWithEditor: 'c'
    commits:
      renameCommit: 'R'
      renameCommitWithEditor: 'r'
