git:
  paging:
    colorArg: always
    pager: delta --paging=never
  pull:
    mode: 'rebase'

gui:
  showFileTree: true
  sidePanelWidth: 0.25
  skipstashwarning: true
  skipunstagelinewarning: false
  theme:
    lightTheme: true
    activeBorderColor:
      - black
      - bold
    inactiveBorderColor:
      - white

startuppopupversion: 1
notARepository: 'skip'
keybinding:
    files:
      commitChanges: 'C'
      commitChangesWithEditor: 'c'
      toggleTreeView: 't'
    commits:
      renameCommit: 'R'
      renameCommitWithEditor: 'r'
